ALTER TABLE FORNECEDOR ALTER COLUMN ESTADO DROP NOT NULL;
ALTER TABLE FORNECEDOR ALTER COLUMN CEP DROP NOT NULL;
ALTER TABLE FORNECEDOR ALTER COLUMN CIDADE DROP NOT NULL;
ALTER TABLE FORNECEDOR ALTER COLUMN BAIRRO DROP NOT NULL;
ALTER TABLE FORNECEDOR ALTER COLUMN LOGRADOURO DROP NOT NULL;
ALTER TABLE FORNECEDOR ALTER COLUMN NUMERO DROP NOT NULL;
ALTER TABLE FORNECEDOR ALTER COLUMN COMPLEMENTO DROP NOT NULL;
