CREATE TABLE IF NOT EXISTS CATEGORIA (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL
);

INSERT INTO CATEGORIA(NOME) VALUES ('Aluguel');
INSERT INTO CATEGORIA(NOME) VALUES ('Automóvel');
INSERT INTO CATEGORIA(NOME) VALUES ('Educação');
INSERT INTO CATEGORIA(NOME) VALUES ('Impostos');
INSERT INTO CATEGORIA(NOME) VALUES ('Lazer');
INSERT INTO CATEGORIA(NOME) VALUES ('Espostes');
INSERT INTO CATEGORIA(NOME) VALUES ('Cimentos');
INSERT INTO CATEGORIA(NOME) VALUES ('Madeira');
